{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "miloagent.fullname" . }}
  labels:
    {{- include "miloagent.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  port:
    targetPort: web
  tls:
    termination: {{ .Values.route.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
  to:
    kind: Service
    name: {{ include "miloagent.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
