apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miloagent.fullname" . }}-env
  labels:
    {{- include "miloagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  MILO_WEB_USER: {{ .Values.env.MILO_WEB_USER | quote }}
  MILO_WEB_PASS: {{ .Values.env.MILO_WEB_PASS | quote }}
  MILO_WEB_TOKEN: {{ .Values.env.MILO_WEB_TOKEN | default "" | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.env.TELEGRAM_BOT_TOKEN | default "" | quote }}
  TZ: {{ .Values.env.TZ | default "UTC" | quote }}
